version: '3'
services:
  app-test:
    build: .
    volumes:
    - ./:/var/www
    depends_on:
      - app-test-mysql
      - app-test-redis

  app-test-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: app-test
      MYSQL_ROOT_PASSWORD: test123

  app-test-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app-test

  app-test-redis:
    image: redis:alpine
    command: redis-server
    restart: always
    expose:
      - 6379
